### ISSUE TITLE
Can't find the map when it's inside a shadow DOM

### ISSUE THREAD

**Issue by A-Behairi** [EOX-A/EOxElements#1089]
In the case of the map element living inside a Shadow DOM; passing the map selector as a string in the `for` property is not possible.

I suggest having the option to support passing a function or having a property that can take the shadow root host element and select the map from inside of it.

for example:
```js
for: {
 map: 'eox-map',
 shadowElement: 'eo-dash'
}
```

**Comment by santilland** [comment]
As we discussed, i think @silvester-pari said as solution we could pass the element directly as for mirroring the solution we do for other eox-elements

**Comment by silvester-pari** [comment]
Kinda like in the [openlayers map](https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html), where the target can be `HTMLElement | string | undefined`.
