### ISSUE TITLE
Remove default styling of `eox-layout`

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/EOxElements#1110]
The gray background etc. is good for debugging, but shouldn't be the default. Maybe enabled via a convenient `debug` attribute?

![image](https://github.com/user-attachments/assets/16979403-75ec-4896-93cd-e2cc2dec7bb4)

**Comment by santilland** [comment]
We could consider a debug flag for most/all eoxelements? Maybe something that could be set globally? Which adds more logging among other things?
But yes, in general i would remove the grey as default
