### ISSUE TITLE
Nested layers order

### ISSUE THREAD

**Issue by A-Behairi** [EOX-A/EOxElements#1251]
Nested layers inside group layers gets reversed sometimes. In my case this happened in [eodash](https://github.com/eodash/eodash), to investigate this further I debugged `oldLayers` & `newLayers` inside `set layers` property.

in the following image the map renders the layers in the right order
<img width="1800" alt="Screenshot 2024-09-11 at 13 09 50" src="https://github.com/user-attachments/assets/2cea6266-de2b-4c19-85bc-c5acdb30dbe6">

and the wrong order in this case:
<img width="1800" alt="Screenshot 2024-09-12 at 16 51 53" src="https://github.com/user-attachments/assets/d4de904e-c069-4787-8e69-0527f820b5a6">

although the layers passed have the same order

**Comment by A-Behairi** [comment]
The layercontrol was removed in the explained example, I think it's more related to the sorting and reversing of the layers in the map.

**Comment by silvester-pari** [comment]
Fixed in https://github.com/EOX-A/EOxElements/pull/1321
