### ISSUE TITLE
Provide option to not include title in navigation bar

### ISSUE THREAD

**Issue by santilland** [EOX-A/EOxElements#1253]
Currently whenever using a title (##) it will be included in the navigation bar (if enabled).
One user wants to use a title (for example the section begin a map tour) but without it being included in the navigation bar. Longer stories have multiple titles (sections) and the navbar does not have much space.
I see two potential ways of doing this:
* a way to disable it per title 
* a special configuration entry for the navbar where you can specify which titles should be included?

Any other ideas? Or workarounds that could be utilized?

**Comment by silvester-pari** [comment]
Per title it could be done as attribute, e.g. `<!-- nav="false" -->`. For the entire navbar we hav the `nav` state, but this isn't anything that is accessible to the end-user writing md I guess. Or maybe using frontmatter (similar to `showNav`)?

**Comment by santilland** [comment]
Agreement on using `<!-- nav="false" -->` after discussion
