### ISSUE TITLE
Introduce flatgeobuf to eoxmap as a possible format

### ISSUE THREAD

**Issue by lubojr** [EOX-A/EOxElements#1270]
It would be great to include support for loading a flatgeobuf cloud optimized vector data format https://www.npmjs.com/package/flatgeobuf

https://guide.cloudnativegeo.org/flatgeobuf/flatgeobuf-in-js.html

Example how it was used in eodash v4

https://github.com/eurodatacube/eodash/pull/1631/files#diff-0d6cb8beb4a03a94cdb041528f0c2583093011bc7884f413735bc14d24d0d3d5R187-R230

**Comment by silvester-pari** [comment]
Probably best suited for the "advanced layers and sources"
