### ISSUE TITLE
Date range filter can not access nested property

### ISSUE THREAD

**Issue by lubojr** [EOX-A/EOxElements#1274]
Following config 
```json
{
  "key":"started",
  "title":"Started",
  "type":"range",
  "format":"date"
}
```
with range date filter works (values are populated)

but a nested key is not accepted

```json
{
  "key":"properties.started",
  "title":"Started",
  "type":"range",
  "format":"date"
}
```

sample items to test:
```json
{
  "properties":{
    "started":"2024-09-19T12:46:24.792000"
  }
}
```
```json
{
  "started":"2024-09-19T12:46:24.792000"
}
```

**Comment by silvester-pari** [comment]
It seems like the [code for using nested properties](https://github.com/EOX-A/EOxElements/blob/40a8d4746fc55b0203992adbb64dcdc9f3c065b4/elements/itemfilter/src/methods/itemfilter/filter-apply.js#L68) is not reached for `type: range` filters ([it returns](https://github.com/EOX-A/EOxElements/blob/40a8d4746fc55b0203992adbb64dcdc9f3c065b4/elements/itemfilter/src/methods/itemfilter/filter-apply.js#L56) beforehand).
