### ISSUE TITLE
Allow to disable capitalization of results of ItemFilter

### ISSUE THREAD

**Issue by lubojr** [EOX-A/EOxElements#1277]
The capitalization functionality is useful in most cases (dashboards) and should be enabled by default, but there are cases where it produces wierd undesired results like with UUID codes which get capitalized only if they start with a letter and so on.

Ideally the functionality should be possible to be disabled by config.

**Comment by silvester-pari** [comment]
Implemented with https://github.com/EOX-A/EOxElements/pull/1285.
