### ISSUE TITLE
Pre-set filters do not show up in chips in inline mode

### ISSUE THREAD

**Issue by viktoraronfarkas** [EOX-A/EOxElements#1365]
When setting the pre-set filters in the itemfilter in inline mode, the chips are not rendered, only the selection is when the filter is opened.

<img width="1308" alt="Screenshot 2024-11-14 at 15 28 48" src="https://github.com/user-attachments/assets/f727154b-c049-460b-9034-aa254fb1f746">

Update: It seems to work with the range filter. 
<img width="1308" alt="Screenshot 2024-11-14 at 16 35 09" src="https://github.com/user-attachments/assets/f890867b-9476-4604-9a17-de07c6adb07b">

**Comment by silvester-pari** [comment]
This is a bug, it should actually recognize that a state has been set by the developer and set the `dirty` proeprty correctly.

In the meantime, as a workaround, you can manually set the `dirty` property:

```js
        {
          key: "code",
          title: "Codes",
          type: "multiselect",
          placeholder: "Search codes",
          expanded: true,
          dirty: true, // set this! when we fix it, this should be set automatically
          state: {
            E10a2: true,
          },
        },
```

**Comment by StefanBrand** [comment]
Proposed workaround does not work for certain filter types:

- `range`: has no `dirty` property (functional)
- `spatial`: does not print geometry type in chip (cosmetic)
  ![image](https://github.com/user-attachments/assets/428e670d-987f-42de-9e67-570e7b9a6f2a)
