### ISSUE TITLE
Shape upload/paste

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/EOxElements#137]
It would be nice if the user could copy/paste or upload/drag-n-drop a feature instead of drawing. E.g. a GeoJSON, other formats to follow. Inspiration could be taken from e.g. http://geojson.io/

**Comment by lubojr** [comment]
Feature would be nice to have **enhancement** for eodash v5 in my opinion, as it was mentioned as a possible enhancement in the past during ui redesign.
