### ISSUE TITLE
Add layer from STAC

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/EOxElements#140]
It would be nice to create a map layer by pointing to a STAC collection or STAC item.

This could be a helper function the `eox-map` provides, e.g. `EOxMap.addStacLayer("<exampleurl>/collection.json", options)`.

Inspiration could be taken from https://github.com/stac-utils/stac-layer

**Comment by silvester-pari** [comment]
@m-mohr do you have any insight into [stac-layer](https://github.com/stac-utils/stac-layer) and how "modular" it is? Could it be either forked to work with OpenLayers, or could OpenLayers support be added with some (minor to medium) effort?

**Comment by m-mohr** [comment]
stac-layer was completely rewritten recently to be based on top of stac-js. Based on stac-js I also prepared code for OpenLayers at https://github.com/tschaub/openlayers/tree/stac-js, but it's not complete yet and still needs some work. Once that's done, the plan is to migrate stac-browser to OpenLayers. But the initial client deprioritized the work, so it could take some time for this to finish unless EOX steps in and asks me to continue the work under their contract.

**Comment by silvester-pari** [comment]
Implemented in https://github.com/EOX-A/EOxElements/pull/208 :tada:
