### ISSUE TITLE
Interaction pointer doesn't get assigned when updating a layer

### ISSUE THREAD

**Issue by A-Behairi** [EOX-A/EOxElements#1404]
The pointer doesn't show when a click interaction is added to a layer that already exists. For example when updating the user provided selection layer in the drawtools 
https://github.com/EOX-A/EOxElements/blob/c6bd1ce6059d6ab15d34287da9be7ae4201b38a1/elements/drawtools/src/methods/draw/init-selection.js#L61

**Comment by santilland** [comment]
To extend on how this creates an issue in eodash, we previously create a feature layer that we want to utilize as source for feature selection using an eox-form that uses the draw-tools based format.
This layer gets the interaction activation afterwards, and hovering over a feature does not show the hand pointer cursor, not making clear that interaction with the feature is possible.
It would be great if this issue can be explored.

**Comment by A-Behairi** [comment]
closed by #1434
