### ISSUE TITLE
Enhance elements general UI

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/EOxElements#143]
This is an ongoing task to improve the UI of the EOxElements. Basic functionality should be usable without any styling, but we want to provide a default style to make it look nice for the end user without much effort.

Some steps necessary:
- [x] split up necessary styles for functionality and EOX styles
- [x] add EOX style for all elements following material design (as much as possible) and material design icons
- [x] add option to change the primary color for the EOX style?
- [x] make it easy for the developer to add additional styles?

Current state of styling
- `eox-chart`: basic styling, not fully responsive yet
- `eox-drawtools`: basic styling
- `eox-itemfilter`: styling complete for now
- `eox-layercontrol`: advanced styling, find functionality missing
- `eox-map`: not styled yet, maybe provide some color styling for the controls (zoom, attribution, etc)
- `eox-timecontrol`: basic styling

**Comment by silvester-pari** [comment]
a `styleOverride` functionality was introduced for itemfilter in https://github.com/EOX-A/EOxElements/commit/f51068a7945560093a98a5cd86137fcb2451ef4f. Maybe this could be a good functionality for all of the elements.

**Comment by lubojr** [comment]
styling via variables is currently being done in https://github.com/EOX-A/EOxElements/pull/616
