### ISSUE TITLE
Add "point" drawing functionality

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/EOxElements#149]
The current implementation only supports drawing polygons. It would be nice to at least add "point" as option.

In previous apps we had the situation where a server API needed a polygon as input but the UI needed a point selection. We mitigated this by creating a buffer around a clicked point and emitting that. So the use cases could be:
- select a point on a map, emit a point
- select a point on a map, but emit a polygon which buffers the point

**Comment by RobertOrthofer** [comment]
the `draw`-functionality of the `map`-element already submits a CustomEvent `drawend`, where additional information like a ready-to-use geojson is attached. We tried to move away from this concept, as it seems redundant to the normal event, that the ol-map emits. 
Maybe we should expose some methods to create these custom formats? Something that can easily create the needed output (geojson, buffered point, etc) with the information the callback of the ol-events provide (like a coordinate or a feature)

**Comment by silvester-pari** [comment]
Point drawing available, buffer helper function now introduced in https://github.com/EOX-A/EOxElements/pull/231.
