### ISSUE TITLE
Tests: `npm run watch:all` breaks map element

### ISSUE THREAD

**Issue by RobertOrthofer** [EOX-A/EOxElements#154]
In the current setup, something is interfering with the `map`-Element when `npm run watch:all`. It works fine when watching only via `npm run watch --workspace=@eox/map`.

This issue can be recreated by running `npm run watch:all` and running the `drawInteraction`-test. The `getLayerById`-method for some reason expects 3 parameters, but that method only requires 2, as in the `map`-Element branch, leading to invalid inputs.

**Comment by silvester-pari** [comment]
The `watch:all` didn't seem to work as intended, so it was removed from the scrips. The recommended way is to first `build:all` and then watch the elements that are being worked on individually (in separate terminals).
