### ISSUE TITLE
Replace `getFlatLayersArray` with native OL `getAllLayers`

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/EOxElements#225]
https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html#getAllLayers

**Comment by RobertOrthofer** [comment]
The ol-Implementation `getAllLayers` does not return group layers themselves, only the "real" layers.
So, at the current `groupLayer`-Test, our `getFlatLayersArray` returns 4 Layers, while `getAllLayers` only returns 2 (the 2 group layers are omitted).

I am not sure which one suits our use cases better. Most of the time, layers should be accessed directly via their ID.

**Comment by silvester-pari** [comment]
Thanks for the research! In that case, and since we need to find group layers via ID as well, I'd say we keep our solution for the foreseeable future.
