### ISSUE TITLE
Programmatically select feature on map

### ISSUE THREAD

**Issue by StefanBrand** [EOX-A/EOxElements#226]
For feature parity with the previous map element, we need a way to select a feature programmatically. I.e. the app starts and a feature is already highlighted from the beginning.

**Comment by StefanBrand** [comment]
The current workflow is:
1. read feature ID from query params
2. ask backend for coordinates of feature
3. pan map to those coordinates
4. highlight feature

**Comment by RobertOrthofer** [comment]
In the case of a `VectorTile`-Layer we cannot guarantee that the feature is available when the programmatic selection is initiated, so we would need to zoom to the location first. When working with slow tiles we could try to prevent the user from interacting with the map until everything is loaded and the feature is available.

I think we would need a list of IDs of features to be highlighted (if multi-select is a thing), as well as a single extent containing these features.

**Comment by silvester-pari** [comment]
> The current workflow is:
> 
> 1. read feature ID from query params
> 2. ask backend for coordinates of feature
> 3. pan map to those coordinates
> 4. highlight feature

In my opinion, steps 1-3 would be application logic, and only step 4 would be a common functionality for the map element. So in the eox-map, we add functionality to highlight a feature **if** it is currently on the map, otherwise it could return an error/info that the feature is not currently on the map.

**Comment by RobertOrthofer** [comment]
I would implement this as a method of an existing `select`-interaction, as this would handle the styling and management of selected features
