### ISSUE TITLE
TypeError: this.findLayerById(...) is undefined

### ISSUE THREAD

**Issue by StefanBrand** [EOX-A/EOxElements#230]
In a Vue app, I modify the layers object (in particular changing id and source url) and then call `setLayers()` on the map.  **Edit:** One has to note that I modify the id of a layer inside a layer group.

I get this error:

```js
Uncaught (in promise) TypeError: this.findLayerById(...) is undefined eox-layercontrol.js:2538
    _$Ej eox-layercontrol.js:201
    AsyncFunctionNext self-hosted:852
    (Async: async)
    requestUpdate eox-layercontrol.js:190
    set eox-layercontrol.js:99
    _updateControl eox-layercontrol.js:2332
    render eox-layercontrol.js:2386
    dispatchEvent main-e0d188f8.js:799
    notify main-e0d188f8.js:1057
    set main-e0d188f8.js:1086
    updateLength_ main-e0d188f8.js:1376
    removeAt main-e0d188f8.js:1343
    pop main-e0d188f8.js:1307
    clear main-e0d188f8.js:1232
    setLayers main-e0d188f8.js:8808
    setLayers main-e0d188f8.js:61261
    selectedLayer ParcelMap.vue:416
    VueJS 5
    onRouteChange index.js:137
    VueJS 11
    init vue-router.esm.js:3005
    forEach self-hosted:203
    init vue-router.esm.js:3004
    updateRoute vue-router.esm.js:2414
    transitionTo vue-router.esm.js:2263
    confirmTransition vue-router.esm.js:2402
    step vue-router.esm.js:2084
    step vue-router.esm.js:2091
    step vue-router.esm.js:2091
    runQueue vue-router.esm.js:2095
    confirmTransition vue-router.esm.js:2397
    step vue-router.esm.js:2084
    step vue-router.esm.js:2088
    iterator vue-router.esm.js:2384
    resolve vue-router.esm.js:2127
    once vue-router.esm.js:2203
    (Async: promise callback)
    resolveAsyncComponents vue-router.esm.js:2150
    flatMapComponents vue-router.esm.js:2171
    map self-hosted:221
    flatMapComponents vue-router.esm.js:2171
    map self-hosted:221
    flatMapComponents vue-router.esm.js:2170
    resolveAsyncComponents vue-router.esm.js:2106
    iterator vue-router.esm.js:2362
```

These are the lines referenced in the error message:

https://github.com/EOX-A/EOxElements/blob/3368698225d9df86c2417563b799834e350bcab4/elements/layercontrol/src/main.ts#L393-L396

**Comment by StefanBrand** [comment]
I've added two test cases that demonstrate the issue of duplicated layers to [layercontrol/fix/duplicated-layers](https://github.com/EOX-A/EOxElements/tree/layercontrol/fix/duplicated-layers).

![image](https://github.com/EOX-A/EOxElements/assets/8948865/fc2ab088-27d2-4d28-b6ee-b59a37204cf2)

**Comment by silvester-pari** [comment]
Thank you for this, I also added a component test showcasing this issue, noting that the component test does not use a real map (just a mock), so the error is definitely inside the layercontrol and not the map.

It seems like only adding layers once via `setMap()` is reflected by the layercontrol, but not changing the layers by calling `setMap()` again afterwards.

Needs more investigation.

**Comment by silvester-pari** [comment]
Should be fixed with https://github.com/EOX-A/EOxElements/pull/250.
