### ISSUE TITLE
Updating `@eox/map` to 0.6.0 breaks all of Layer Control

### ISSUE THREAD

**Issue by spectrachrome** [EOX-A/EOxElements#235]
**_Bug:_**

The Layer Control exhibits a bug on all browsers which prevents the rendering of the custom elements found in the `index.html` example.

It seems that the content is simply not rendered into the template.

**_Solution:_**

Change the version of `@eox/map` back to `0.5.4`:

```javascript
import "https://unpkg.com/@eox/map@0.5.4";
```

_(From iOS Safari)_
<img width="846" alt="Screenshot 2023-09-05 at 13 15 47" src="https://github.com/EOX-A/EOxElements/assets/94269527/cd037673-26bb-40d4-a819-33615e05b8a9">
 
 
![IMG_0676](https://github.com/EOX-A/EOxElements/assets/94269527/4334af0a-295c-4864-b286-46870cbec1d8)

**Comment by RobertOrthofer** [comment]
2 things:

First, the `style` definition for vector layers does not accept strings for numerical fields anymore, so changing the current styles true number values should fix that (otherwise the layer will not be generated):

```
"style": {
  "circle-radius": 10,
  "circle-fill-color": "red",       
   "circle-stroke-color": "black",
  "circle-stroke-width": 2,
  "stroke-color": "black",
  "stroke-width": 5,
  "fill-color": "red"
}
```

Second, it looks like the layer generation went async. The generation of the layers "should" be synchronous, only sources and styles might be async. This is not intentional, I have to look into that. For now you can use the `addDraw`-method after a small `setTimeout()`

**Comment by spectrachrome** [comment]
Thank you very much for the detailed instructions!

I will try this out first thing Monday morning to see if I can get the layer control running with `0.6.0`. Regarding the complexity of this project, I would strongly recommend to document changes in a `CHANGELOG.md` file using the [Keep A Changelog](https://keepachangelog.com/en/1.1.0/) format for each of the components to inform other developers about relevant changes made between versions.

Have a great weekend 🙌

**Comment by silvester-pari** [comment]
@spectrachrome agreed about the changelog, feel free to make a good example and start generating changelogs for the changes you implemented so far :wink: 
On a more serious note, we will definitely need an automated changelog system before hitting v1.0.0, but for now the PR descriptions are all we have.

As for the synchronous layer generation, this might be changed again, but generally it might be best to wait for map load before doing anything with it:
```
      const eoxMap = document.querySelector("eox-map");
      eoxMap.addEventListener("loadend", () => {
        eoxMap.addDraw("drawLayer", {
          id: "drawInteraction",
          type: "Point",
        });
      });
```

Opened a dedicated issue for this: https://github.com/EOX-A/EOxElements/issues/240
