### ISSUE TITLE
`EOxMap.getLayerById(...)` does not traverse layer tree recursively

### ISSUE THREAD

**Issue by spectrachrome** [EOX-A/EOxElements#239]
### Problem Description

Regarding the functionality of deleting layers within the Layer Control, the following part of a Cypress test is unable to correctly determine if a layer with a given ID exists within the map or not.

```typescript
// Verify the deletion of the map layer itself.
cy
  .get("eox-map")
  .then($el => {
    const eoxMap = <EOxMap>$el[0];
    let layer;
    try {
      // TODO / WARNING: This part of the test is broken!
      //
      // The following function call does not handle map layers recursively. The test fails 
      // as expected when presented with `group1`, but succeeds with `osm`!
      //
      // This needs to be corrected in `EOxMap` before we can correctly implement this test.
      layer = eoxMap.getLayerById('s2');
      //                  ^---------------- add support for tree traversal
    } catch (error) {
      // Catch the error here so we can ignore it. For debugging:
      // console.error(error)
    }
    assert.equal(layer, undefined, 'OSM Layer should not be found');
  });
```

The function succeeds with root-level nodes but fails to find any other group or layer IDs.

### Proposed Solution

Implement `EOxMap.getLayerById` in a way which iterates over the layer tree recursively by calling itself when presented with a (sub)child to prevent the test from passing too easily.

**Comment by silvester-pari** [comment]
0.6.0 introduces exactly this functionality, see https://github.com/EOX-A/EOxElements/pull/229. Seems like you downgraded the map (see your other issue).
