### ISSUE TITLE
Allow visualization of colormap legend in layer control

### ISSUE THREAD

**Issue by santilland** [EOX-A/EOxElements#245]
This was discussed today in GTIF meeting. In order to help understand which colormap is used by which layer it would be great to have also the colormap information inside the layer.
Maybe in the future the colormap could also be a slider that allows setting min/max range? or be interactive to show the value of a color?
Thinking further it might be a more extended tool that allows band combinations somehow, not sure how that would mix.
Here a concept screenshot
![image](https://github.com/EOX-A/EOxElements/assets/4036819/73b52e54-6b98-4ddd-8b66-9a3b3137e530)

**Comment by silvester-pari** [comment]
As of version 0.7.0 we have the "tools" concept, where we could use either the "info" or the "config" tool for this purpose. In the "info" tool (supports displaying the layer `description` including HTML) it could be just an image in the correct size, in the "config" tool we could dynamically calculate the scale and offer a real range slider.

**Comment by santilland** [comment]
Could we maybe use something like this? If we assume we have d3 available? Would not want to integrate d3 just for this, but i think this would be very helpful:
https://observablehq.com/@d3/color-legend
