### ISSUE TITLE
Have info button (per layer) that allows opening more information

### ISSUE THREAD

**Issue by santilland** [EOX-A/EOxElements#246]
I don't really have a concrete opinion on what exactly the info button should show. Considering a more Stac approach it could show the description, but probably needs to be shorter. 
Another option is that a sort of template or info object can be passed that will be rendered in some sort of panel.
Example screenshot:
![image](https://github.com/EOX-A/EOxElements/assets/4036819/133d23b7-f033-4b19-8233-b6a51624de0e)

**Comment by silvester-pari** [comment]
As of version 7, "tools" have been implemented, whereas one of them is the "info" tool. It displays a layer `description` property and currently supports HTML. If needed in future, we could also add a markdown renderer.

![image](https://github.com/EOX-A/EOxElements/assets/26576876/2291713f-bef2-4727-ad77-613041142153)
