### ISSUE TITLE
If a layer has minZoom/maxZoom set, change CSS color based on map current view zoom

### ISSUE THREAD

**Issue by lubojr** [EOX-A/EOxElements#248]
If layer is currently not seen on the map view due to maxZoom/minZoom, this should be ideally reflected in the layercontrol by a different style/color for example.

**Comment by santilland** [comment]
Cool idea! Maybe like a warning sign and when you hover over it, it shows a message? Something like... "This layer can't be shown on the current zoom level" ?

**Comment by lubojr** [comment]
The official (vanilla) OL layer control used I think disabling of the input field + grey color, which sounds more mobile friendly to me, but at the same time disabling the field completely might be too limiting (if user wants to disable the layer before zooming towards it for whatever reason)

**Comment by silvester-pari** [comment]
Implemented in https://github.com/EOX-A/EOxElements/commit/09f5288de6e86aab72f8f6cee0ba4cce337c7cfe
