### ISSUE TITLE
Fix storybook mobile layout

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/EOxElements#257]
Might need another meta tag plus additional css styling to work properly?

**Comment by silvester-pari** [comment]
Seems to be a known bug: https://github.com/storybookjs/storybook/issues/23723

**Comment by lubojr** [comment]
Will be a part of 8.0.0. release. I have set a watcher to the github repo to be notified on releases

**Comment by lubojr** [comment]
@silvester-pari Storybook 8.0.0 has been released.
https://github.com/storybookjs/storybook/releases/tag/v8.0.0
Migration guide from 6 to 8: https://storybook.js.org/docs/migration-guide
