### ISSUE TITLE
selectStyleLayer does not respect minZoom/maxZoom

### ISSUE THREAD

**Issue by StefanBrand** [EOX-A/EOxElements#267]
After using using `addSelect` on a layer with `minZoom` , the map still makes tile requests when zooming out beyond `minZoom`.

The problem seems to be that we don't carry over `minZoom`/`maxZoom` to the `selectStyleLayer`:

https://github.com/EOX-A/EOxElements/blob/79b91cfde7966bd85994fedece1109e94d607860/elements/map/src/select.ts#L83-L92

**Comment by silvester-pari** [comment]
Fixed in https://github.com/EOX-A/EOxElements/pull/289
