### ISSUE TITLE
Cannot set style using style constructors

### ISSUE THREAD

**Issue by StefanBrand** [EOX-A/EOxElements#285]
When I try to set the style using the old-school style constructors (necessary to apply a pattern), I get a `TypeError`:

```
Uncaught TypeError: t is null
Cd@http://localhost:8080/js/chunk-vendors.js:65170:13
renderFeature@http://localhost:8080/js/chunk-vendors.js:77955:13
k@http://localhost:8080/js/chunk-vendors.js:77654:26
updateExecutorGroup_@http://localhost:8080/js/chunk-vendors.js:77667:57
prepareTile@http://localhost:8080/js/chunk-vendors.js:77583:55
getTile@http://localhost:8080/js/chunk-vendors.js:77594:73
renderFrame@http://localhost:8080/js/chunk-vendors.js:77176:24
render@http://localhost:8080/js/chunk-vendors.js:54754:55
renderFrame@http://localhost:8080/js/chunk-vendors.js:55275:19
renderFrame_@http://localhost:8080/js/chunk-vendors.js:58216:42
animationDelay_@http://localhost:8080/js/chunk-vendors.js:58086:44
```

I added a failing test case here: https://github.com/EOX-A/EOxElements/compare/main...map/style-constructor-test

**Comment by RobertOrthofer** [comment]
The old way of creating styles via JSON (via invocation of Style, Fill, etc) has been suspended in favor for the new `flatStyles`. Your "should" still be able to create your own style by setting the style from the parent application by setting the style directly on the layer after layer generation, instead of the JSON, if you have a compatible version of `ol` (currently we use `8.1.0`).

However, this is not advised, as using different instances of `ol` can create some problems. Maybe we should create an API-way of creating the pattern as part of the EOx-Map.

On a side note, if we keep getting to the point where we wish we would have access to the native ol styles classes to create more complex styles, maybe we can expose them as part of the EOx-Map, as some kind of semi-API-workaround.

**Comment by StefanBrand** [comment]
> Your "should" still be able to create your own style by setting the style from the parent application by setting the style directly on the layer after layer generation, instead of the JSON, if you have a compatible version of `ol` (currently we use `8.1.0`).

Does this mean that even if I access the OL map like this `document.querySelector("eox-map").map`, it will still use the OL version of the parent application? :monocle_face: We currently install OL 6.5.0 in the parent application, but I wouldn't expect that this would influence how I interact with the OL instance inside the new map web component.

**Comment by StefanBrand** [comment]
Ah, Silvester explained to me that if I `import { Style } from ol/style`, I get the one from the parent application. Makes sense.

On the other hand, the failing test case demonstrates that this is a problem of the component, not of an integration into a parent application.

**Comment by silvester-pari** [comment]
@RobertOrthofer I'd see two options:
- expose the Style classes via the custom element
- offer a second build of the element that doesn't bundle OL but lets the user allow installing a custom OL version as peer dependency (on his/her own risk, without guarantee that the versions would be compatible). Something like `import "@eox/map"` (full bundle including OL) versus `import "@eox/map/minimal.js"` (no OL bundled).

What's your opinion on this?

**Comment by RobertOrthofer** [comment]
honestly i would prefer nr 1, as we need the Style constructors as part of the element anyways. Offering a build without one of the most central parts of the  application seems risky, and debugging future problems could cause some headache.

**Comment by silvester-pari** [comment]
@StefanBrand I just saw in the test you're trying to stringify the Style including the Fill, so maybe the error comes from that? https://github.com/EOX-A/EOxElements/compare/main...map/style-constructor-test#diff-7089e9405e48341dff7dd1fd11ce21ea74f503bfd854325503706fd326c54937R54

**Comment by StefanBrand** [comment]
This will cover my use-case: https://github.com/openlayers/openlayers/pull/15318
