### ISSUE TITLE
Events missing from Storybook

### ISSUE THREAD

**Issue by StefanBrand** [EOX-A/EOxElements#286]
It would be useful to have the emitted events documented in the Storybook. I'm using the `loadend` and `select` events of the map, but I'm curious which other events are available. Are all OL events forwarded?

**Comment by silvester-pari** [comment]
In general, it seems like our current web component analyzer only recognizes custom events if they are dispatched inline, e.g.
```
// Won't include in custom-element.json
const myEvent = new CustomEvent(...)
this.dispatchEvent(myEvent)

// Will include in custom-element.json (and therefore in Storybook API docs)
this.dispatchEvent(new CustomEvent(...))
```

In regards to native OL events, they're not currently bubbled up to the parent, but this is something we could look into.
