### ISSUE TITLE
addOrUpdateLayer removes all styles

### ISSUE THREAD

**Issue by StefanBrand** [EOX-A/EOxElements#287]
When I call addOrUpdateLayer with a different style (possibly multiple times), all features disappear.

**Comment by RobertOrthofer** [comment]
I could not reproduce this issue, however, https://github.com/EOX-A/EOxElements/pull/298 removes some unneeded `async` stuff, so maybe this has to do with it.
Can you maybe share your layer-JSON, so i can have a closer look?

**Comment by StefanBrand** [comment]
If it comes up during our hackathon next week, I'll copy over the layer JSON.

**Comment by StefanBrand** [comment]
If it comes up during our hackathon next week, I'll copy over the layer JSON.

**Comment by StefanBrand** [comment]
I am not using this function anymore and rely on `setLayers`. Possibly the issue was related to an outdated layercontrol, like #288
