### ISSUE TITLE
Calling setLayers multiple times results in blank map

### ISSUE THREAD

**Issue by StefanBrand** [EOX-A/EOxElements#288]
Initially, layers reload quickly when calling `setLayers`. Then rerendering becomes slower and after about three times the map simply stays blank and does not rerender (no layer at all, not even base layers).

**Comment by RobertOrthofer** [comment]
I cannot reproduce this issue, can you provide a minimal example as layer-json where this occurs?
Right now im on restructuring the the EOxMap to use reactive properties, maybe this issue will resolve itself after the changes.

**Comment by StefanBrand** [comment]
@RobertOrthofer Here is a Firefox performance profile. It seems that each time I switch app pages, layercontrol does more work. 

https://share.firefox.dev/3QDJ9SS

same for offline usage: [Firefox 2023-11-13 09.28 profile.json.gz](https://github.com/EOX-A/EOxElements/files/13332683/Firefox.2023-11-13.09.28.profile.json.gz)

**Comment by StefanBrand** [comment]
My bad, I thought I had updated layercontrol to the latest version. Cannot reproduce in v0.9.0. Closing (again).
