### ISSUE TITLE
Generic way of adding style overrides

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/EOxElements#325]
Each element needs some way to override the styling; some concepts are already present in the itemfilter, but no default has been developed yet.

Related to the question of shadow vs. non-shadow.

**Comment by silvester-pari** [comment]
Interesting summary here: https://nolanlawson.com/2021/01/03/options-for-styling-web-components/

**Comment by lubojr** [comment]
Theming done via style variables in https://github.com/EOX-A/EOxElements/pull/616
