### ISSUE TITLE
Attached interactions do not respect minzoom

### ISSUE THREAD

**Issue by StefanBrand** [EOX-A/EOxElements#439]
I'm setting the `minZoom` on a `VectorTile` layer definition. This works for the layer itself, but not for its attached interactions. Hover and select still trigger. While this can probably be worked around, I would expect the map to handle this automatically.

![Peek 2023-11-21 13-04](https://github.com/EOX-A/EOxElements/assets/8948865/910a07b9-87ee-4e12-a5a5-8d932a7201c3)

Besides, when the app loads with a low zoom level and no geometries are there, the interactions throw an exception:

```js
Uncaught (in promise) TypeError: a is null
    node_modules chunk-vendors.js:78912
    getFeatures main-d40d34f6.js:29894
    getFeatures main-d40d34f6.js:6256
    getFeatures main-d40d34f6.js:14012
    getFeatures main-d40d34f6.js:30202
    a main-d40d34f6.js:80504
    dispatchEvent main-d40d34f6.js:837
    handleMapBrowserEvent main-d40d34f6.js:9439
    dispatchEvent main-d40d34f6.js:837
    relayMoveEvent_ main-d40d34f6.js:7281
    Me main-d40d34f6.js:928
    WL main-d40d34f6.js:7114
    handleTargetChanged_ main-d40d34f6.js:9509
    dispatchEvent main-d40d34f6.js:837
    notify main-d40d34f6.js:1103
    set main-d40d34f6.js:1132
    setTarget main-d40d34f6.js:9768
    firstUpdated main-d40d34f6.js:81785
    _$AE main-d40d34f6.js:267
    performUpdate main-d40d34f6.js:258
    scheduleUpdate main-d40d34f6.js:231
    _$EP main-d40d34f6.js:227
    requestUpdate main-d40d34f6.js:215
    _$Ev main-d40d34f6.js:154
    Ha main-d40d34f6.js:150
    Rl main-d40d34f6.js:549
    dr main-d40d34f6.js:81728
```

Related: #267

**Comment by silvester-pari** [comment]
The implemented solution has two ways of working:
- using the shorthand (only defining the select style) takes the min/maxZoom from the original layer
- using the complete config (defining the complete selection layer) allows setting different min/maxZoom for the original layer and the selection layer, allowing things like showing all geometries on e.g. zoom level 10, but keeping the highlighted geometry all the way up to zoom 0, etc.
