### ISSUE TITLE
COG manipulation as part of layerConfig

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/EOxElements#445]
https://github.com/EOX-A/EOxElements/pull/430 introduced a way to configure the layer source URL parameters via an input form. A similar functionality could be to offer GeoTIFF manipulation in the same tab in a similar way.

Ideas for COG manipulation as part of the layerConfig:
- channel selection and band stretch: https://openlayers.org/en/latest/examples/cog-stretch.html
- changing visualization style: https://openlayers.org/en/latest/examples/cog-style.html
- filtering multiple bands of a COG / multiple COGs in a layer group with each other: see `cogFilters` in https://openlayers.org/en/latest/examples/cog-style.html
- ...

**Comment by lubojr** [comment]
If I am not mistaken, we already do allow this functionality by usage of variables within a style, right? @santilland could you confirm?
