### ISSUE TITLE
Consider adding also a "style config" to layers

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/EOxElements#449]
The `layerConfig` could be expanded to include e.g. vector styling functionalities, such as:
- changing the color scale for features, based on value
- changing if a text label should be rendered on a feature, and which feature property to use for it
- ...

**Comment by lubojr** [comment]
This is already enabled by the style variables concept, right @santilland ?

**Comment by santilland** [comment]
You are right, i think through the style and jsonform that can be passed introduced in this release https://github.com/EOX-A/EOxElements/releases/tag/layercontrol-v0.18.1 we can cover all the functionality listed in the issue, so closing the issue.
Thanks for keeping an eye on things!
