### ISSUE TITLE
layerConfig: handle cases where a tileUrlFunction is set instead of an url

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/EOxElements#450]
Currently, in https://github.com/EOX-A/EOxElements/blob/main/elements/layercontrol/src/components/layerConfig.js#L64 we assume that the source has url(s) set and an array is returned. In case of a `tileUrlFunction`, the `getUrls()` call will return `undefined`: https://openlayers.org/en/latest/apidoc/module-ol_source_XYZ-XYZ.html#getUrls

Ideally we would create a wrapper function which passes the same arguments to the `tileUrlFunction`, but updates the output url params accordingly.

**Comment by lubojr** [comment]
closed by https://github.com/EOX-A/EOxElements/pull/451
