### ISSUE TITLE
Refactoring `drawtools`

### ISSUE THREAD

**Issue by srijitcoder** [EOX-A/EOxElements#453]
- **Atomic Structuring:** This approach facilitates easy management and readability of small chunks of code, allowing us to separate them based on their functionality.

  - `/src/methods`
      - All method and handler functions inside components belong in this folder.
      - Segregating these functions reduces the lines of code within components.
      - We'll place them in individual files like `method1.js`, `method2.js`, and combine them inside `index.js` (to be imported as:

    ```javascript
    import { method1, method2 } from "/methods";
    ```

  - `/src/helpers`
      - Currently, there's only one `helpers.js` file containing multiple functions.
      - We'll separate them into individual files like `helper1.js`, `helper2.js`, combining them in `index.js` (to be imported as:

    ```javascript
    import { helper1, helper2 } from "/helpers";
    ```

  - `/src/components`
      - All components will reside within this folder.

  - `/src/style`
      - All style files will be stored in this folder.

  - `main.js` - Entry point for the library.
  - `enums.js`
      - Contains keywords or objects repeatedly used in our code, placed in uppercase. For example:

    ```javascript
    const DRAW_EVENTS = {
       click: "draw-click",
       hover: "draw-hover"
    };

    DRAW_EVENT.click;
    ```

  - `/stories`
      - All stories will be placed in the `/stories` folder.
      - To prevent unwieldy files, stories will be split into smaller, atomic-structured individual files such as `one.stories.js`, `two.stories.js`.

  - `/test`
      - Test cases within `general.cy.js` will be separately imported from the `/test/cases` folder:

    ```javascript
    import { case1, case2 } from "/cases";

    it("Test case 1", () => case1());
    it("Test case 2", () => case2());
    ```

- Ensuring comprehensive JavaScript type checking.
- Simplification of complex functions.
- Including adequate comments as required.
- Identifying and rectifying any re-rendering or event function triggers.
- Adding more test cases.
- @silvester-pari Can we experiment with Tailwind CSS? (It's an excellent styling library that reduces the need for extensive CSS).

```
- jsonform
- layercontrol
- drawtools
    - src
        - style
            - style.eox.js
            - style.js
        - helpers
            - index.js
            - helper1.js
            - helper2.js
        - methods
            - index.js
            - method1.js
            - method2.js 
        - components
            - index.js
            - control.js
            - list.js
        - main.js
        - enum.js
    - stories
        - one.stories.js
        - two.stories.js
        - config.js
    - test
        - cases
            - index.js
            - case1.js
            - case2.js
```

**Comment by silvester-pari** [comment]
Thanks for your valuable input, this all sounds great. Only thing I am unsure about is styling using Tailwind in comparison with the shadow DOM, I've read some articles that suggest e.g. using tailwind-in-js ([twind](https://twind.dev/)), but that needs to be explored a bit regarding bundle size, styleability etc.

Could we maybe do that in a two-step process? First restructuring of all things js, and as a second step refactoring the HTML + styles?

Here are some general points to keep in the back of our heads while doing the refactoring:

- Component structure: make all sub-components shareable and usable by other elements or as standalone
  - Example: eox-itemfilter has list, autocomplete, multiselect components etc. which could be used as standalone components
  - Example: two-thumb-slider included in jsonform, itemfilter etc.
  - Consideration: a separate "ui" folder/library inside the repository for small-scale components; alternatively treat them as equal to other elements?
- Attributes/properties: make sure component attributes only allow strings, but properties all types; all attributes should also be available as properties
- Unstyled version: offer a pure HTML version that can be completely re-styled by a third party; this probably needs to include some classes that can be styled
- Clear & easy API to change styling (interesting read about styling strategies: https://nolanlawson.com/2021/01/03/options-for-styling-web-components/)
- Depending on which styling strategy is chosen (see above): offer a shadowRoot/non-shadowRoot mode for all sub-components (shadowRoot as default, when used as standalone; non-shadowRoot when embedded in other components as to offer styling via the top-level)
