### ISSUE TITLE
Props are stripped from Storybook code preview

### ISSUE THREAD

**Issue by StefanBrand** [EOX-A/EOxElements#454]
When I view the code for the layercontrol story about tools, all usages look the same:

![image](https://github.com/EOX-A/EOxElements/assets/8948865/e2bbd470-8609-42dd-8a19-fa4afe6ec746)

However, the story source reveals that the example uses the `tools` property:

https://github.com/EOX-A/EOxElements/blob/88b16ee3fab5a23cb9726cbdf07889af912d0402/elements/layercontrol/layercontrol.stories.js#L323-L332

Thus it seems that Storybook strips props from examples.

**Comment by silvester-pari** [comment]
This is a general issue with Sotrybook which we haven't found a good solution for yet. The dynamic args are not displayed in the `code` block, making it currently useless. Maybe there is a Storybook configuration/plugin that renders the args into the code snippet.

**Comment by silvester-pari** [comment]
By changing the source code rendering type to `code` shows the raw input, which might be too much:

![image](https://github.com/EOX-A/EOxElements/assets/26576876/5ace10c6-49d6-4237-9115-cc4d68f0298b)

**Comment by StefanBrand** [comment]
I like that it shows the properties and mostly can be copy-pasted as-is (needs to be adapted to framework, e.g. Vue, of course). This makes the different configurations of `eox-layercontrol` clearer. 

Too bad that the syntax highlighting is a bit off inside the template string. But that's a minor issue.

**Comment by silvester-pari** [comment]
There is also a plugin that can show the HTML in the individual stories, it seems to be a bit more feature-rich (e.g. live updating the HTML when args are changed): https://storybook.js.org/addons/@pateta/storybook-addon-html

Maybe this would be better, and we would remove the code blocks entirely from the docs page :thinking:

**Comment by silvester-pari** [comment]
Found a workardound that somewhat works:

https://github.com/EOX-A/EOxElements/pull/523/commits/901c3cfc3c6d8a03c284637d1358ff680ab4e6db
https://stackoverflow.com/a/77654795/15745944

![image](https://github.com/EOX-A/EOxElements/assets/26576876/c8a93f5f-4b45-4284-90e1-6c46c27a8174)
