### ISSUE TITLE
Drag and drop ordering not working properly in LayerControl.

### ISSUE THREAD

**Issue by viktoraronfarkas** [EOX-A/EOxElements#455]
https://github.com/EOX-A/EOxElements/assets/49757700/3b0266f7-7bad-4778-9424-2f749558ffcd

The dragged item always jumps up to top, no matter what position I am trying to move it to.

**Comment by silvester-pari** [comment]
There seems to be some general issue with this, we have a PR that tries to cover this as well: https://github.com/EOX-A/EOxElements/pull/344
Originally started with #302, but more and more issues with the sorting were found :-(

**Comment by silvester-pari** [comment]
Turns out this erratic jumping behavior is because of a hidden layer that messes up the index.
