### ISSUE TITLE
Consider using renovate instead of dependabot

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/EOxElements#459]
https://github.com/renovatebot/github-action
Renovate seems to come with the "grouping" feature built-in, meaning we'd have less individual dependency update PRs (e.g. "update all patch/minor versions of all packages" etc.

**Comment by lubojr** [comment]
This sounds like a good idea from maintenance perspective

**Comment by silvester-pari** [comment]
I started creating groups for dependabot, and that seems to work nicely as well, e.g. for storybook and typescript related dependencies:
https://github.com/EOX-A/EOxElements/pull/487
https://github.com/EOX-A/EOxElements/pull/486
We'd need to find out which other benefits renovate could bring.
