### ISSUE TITLE
Selection style disappears when panning too much

### ISSUE THREAD

**Issue by StefanBrand** [EOX-A/EOxElements#475]
The video demonstrates the issue. During the first few seconds I make only small pans. In the end I pan for longer and suddenly the selection style disappears. Sometimes this happens earlier, or when the parcel is panned out of view.

[Peek 2023-11-28 09-17.webm](https://github.com/EOX-A/EOxElements/assets/8948865/e3d43bc7-8072-41fe-ae2a-0fa3d5377a71)

**Comment by StefanBrand** [comment]
Do you have a Fiddle for your example?

**Comment by silvester-pari** [comment]
@StefanBrand https://codesandbox.io/p/devbox/eox-map-2xr5d5

**Comment by StefanBrand** [comment]
The selection disappears when calling `addSelect`. Not sure if this API method even exists in v1 of the map. Therefore I'm closing as it is an implementation mistake in our application.
