### ISSUE TITLE
Refactoring CSS Styling with help of Tailwind (Experimental) 

### ISSUE THREAD

**Issue by srijitcoder** [EOX-A/EOxElements#520]
### Context

Currently, the styling within our `monorepos` lacks consistency and maintenance. Some repositories contain redundant styling that could be reused.

### Approach

While exploring resources, I came across an intriguing article titled "Lit web components: Tailwindcss styles at build time" by Michael Warren [article link](https://dev.to/michaelwarren1106/lit-web-components-tailwindcss-styles-at-build-time-44ab). I believe, with modifications to Warren's approach, we can effectively achieve our objectives. His article focuses on an environment similar to `EOxElements`, involving a monorepo structure, the lit framework, distribution with es6, and no bundler.

I intend to address all issues and concerns raised by @silvester-pari regarding Tailwind towards the end but starting with the approach for `EOxElements`:

- We will incorporate only `tailwind`, `autoprefixer`, and `postcss` as `devDependencies` in the root `pkg.json`.
- Exclusively, classic `tailwind` will be used, and not `twind`.
- A task function will be utilized, running during `dev` and `build` processes. This function will scan through all `.css` files within the monorepo, generating `{component}.style.js` from `{component}.css`. We will import this `*.style.js` file into our lit components and use it alongside `unstyled` as demonstrated:

    ```js
    import ListStyle from "./list.style"; 
    import MainStyle from "../main.style";

    export class EOxDrawToolsList extends LitElement {

      render() {
        return html`
          <style>
            ${!this.unstyled && MainStyle}
            ${!this.unstyled && ListStyle}
          </style>
        ...
    ```
  
- `.css` files will be authored and transformed to `.style.js` using the aforementioned task function.
- A reusable set of styles at the `util` level will be generated and employed across the entire `monorepo`.
- Each package will have a designated `main.style.js` (name can be decided) containing the `purged` version of basic tailwind, tailored to the classes utilized within components.

### Q. Bundle size before? And how does it change if more classes are used
> Initially, with basic tailwind purge and a few CSS additions, the size increased from `11KB` to `14KB`. This is a notable improvement over `twind`. If more styles are incorporated, the increase will be comparable to the styles currently included in the components.

```css
/** This will be converted to normal style by the taskl **/
button {
  @apply inline-flex relative center border-0 outline-none rounded-md p-4 h-9 cursor-pointer text-sm uppercase font-medium shadow-md transition-all;
}
```

Converted `*.style.js` (Will be imported in our lit component)

```js
import { css } from "lit";
export default css`
  button {
    display: inline-flex;
    position: relative;
    align-items: center;
    color: #fff;
    border-width: 0;
    outline: none;
    border-radius: 4px;
    padding: 16px;
    height: 36px;
    cursor: pointer;
    font-family: inherit;
    font-size: 0.875rem;
    text-transform: uppercase;
    letter-spacing: 1.25px;                           
    font-weight: 500;
    box-shadow: 0px 3px 1px -2px rgba(0, 0, 0, 0.2), 0px 2px 2px 0px rgba(0, 0, 0, 0.14), 0px 1px 5px 0px rgba(0, 0, 0, 0.12);
    transition-property: box-shadow, transform, opacity, background;
    transition-duration: 0.28s;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  }
`;
```

### Q. It litters the HTML quite a bit, making it harder to read
> We won't directly pass the classes; instead, we will employ the `@apply` function to create element-level classes. This approach ensures readability, as demonstrated in the example.

### Q. It is a CSS framework we are completely unfamiliar with at EOX
> Learning tailwind is straightforward. It provides predefined `classnames`, such as using `bg-red-300` instead of `background: red;`. Additionally, there are helpful VSCode extensions for easy auto-fill and robust documentation available.

### Q. I am unsure of how we could offer an "unstyled" version for any use case where the styling needs to be completely changed (although we can discuss if this is really needed)
> We'll implement the same approach as mentioned in the example - `${!this.unstyled && ListStyle}`.

### Q. I am unsure how style overrides (these are definitely needed in projects) would work; here it would be good to have some more experiments before opting in
> Overriding becomes simple if we write our classes and use tailwind's `@apply` approach. Additionally, we can employ `tailwind.config.js` to add `EOxElement`-specific configurations.

### Q. On a side note, doesn't it need to be part of the dependencies, not devDependencies?
> No, it will remain a `devDependencies` entry. The final style is generated at build time based on the style usage. Tailwind's purging capability removes all unused properties.

### Experiment Status

- Raised PR #517 to experiment with Tailwind (Code is not clean). Also, the watch in `npm run start` is not functional.

PS. - For a more detailed understanding of the approach, refer to Michael Warren's article "Lit web components: Tailwindcss styles at build time" [article link](https://dev.to/michaelwarren1106/lit-web-components-tailwindcss-styles-at-build-time-44ab).

**Comment by santilland** [comment]
From what i can read and seeing the proposed approach i can see the benefit of using it. 
Still i think one should pose the question on how complex of a styling we want to have in the EOxElements to begin with.
If we think enough complexity of styling will be needed, then this approach would be valuable. This is not something i can really evaluate though.
I am also a bit preoccupied about possible building times when developing, this introduces an additional build step, which as far as i see from the article would need to be further refined to have caching, so some additional effort will probably need to be invested.

**Comment by silvester-pari** [comment]
This was replaced by a more minimalistic general approach with #616.
