### ISSUE TITLE
Branch/PR deployments/packages

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/EOxElements#530]
In some situations, it would be handy to have the storybook deployment and/or npm packages for specific branches/PRs. This could be maybe triggered via a manual action trigger if needed.

**Comment by santilland** [comment]
You should be able to add:
`workflow_dispatch:`
to the workflow in order to allow manual triggering from the actions tab on github

**Comment by silvester-pari** [comment]
So it seems thee are two separate things that would be nice:
- Storybook deployment for branches/PRs (doesn't need packages to be published since it bundles the elements code directly)
- npm packages for branches/PRs

**Comment by lubojr** [comment]
More info on manual running of a workflow:

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#providing-inputs
https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
