### ISSUE TITLE
Geolocation with feature display

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/EOxElements#562]
Consider offering a convenient way to access and display geolocation on the map - https://openlayers.org/en/latest/examples/geolocation.html

**Comment by StefanBrand** [comment]
User requirement was stated as follows:

>>>
Geoposition / Location anzeigen und anwenden

anwenden = automatically zoom to position on startup in ParcelMap, e.g. during field visits on tablet
>>>

**Comment by silvester-pari** [comment]
@StefanBrand could this be solved with a map control? So the user clicks on a button within the map and is zoomed to the position?

**Comment by StefanBrand** [comment]
Since we must support both mobile and in-house usage, we should start off with a button that users can push on demand.
