### ISSUE TITLE
Create layer from capabilities xml

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/EOxElements#602]
In the old version of eox-map we had a convenient way to create a layer from capabilities; this was done with the [getCapabilities](https://github.com/EOX-A/EOxElements/blob/v1/packages/map-basic/src/WMTSCapabilitesProvider.vue#L39-L91) method.

We could also add this to the new version of the map by creating a custom layer type, where a layer could be defined like e.g.
```
{
  type: "Tile",
  source: {
    type: "WMTSCapabilities",
    url: "<link to capabilities xml>",
    identifier: "<layer identifier"
  }
}
```

## Relevant resources
- https://openlayers.org/en/latest/examples/wmts-capabilities.html
- https://openlayers.org/en/latest/examples/wmts-layer-from-capabilities.html
- https://openlayers.org/en/latest/apidoc/module-ol_source_WMTS.html#.optionsFromCapabilities
- https://tiles.maps.eox.at/wmts/1.0.0/WMTSCapabilities.xml

**Comment by lubojr** [comment]
Can be used for supporting a web map link of type WMTS: https://github.com/stac-extensions/web-map-links?tab=readme-ov-file#ogc-wmts.

**Comment by silvester-pari** [comment]
Implemented in https://github.com/EOX-A/EOxElements/pull/767
