### ISSUE TITLE
Rename currentTime to currentDate in TimeControl element

### ISSUE THREAD

**Issue by viktoraronfarkas** [EOX-A/EOxElements#648]
Currently, what we call `currentTime` in the TimeControl element, is a date string (according to the Storybook). I suggest we change the name to `currentDate` or `selectedDate` to make the naming more intuitive.

**Comment by silvester-pari** [comment]
I'm a bit unsure about this. True, in the example it is a date string, but it could also be a datetime string. It really depends on what the server expects. Shall we rename the whole element to "DateControl" then? :wink: 

Plus, you could even change other things, such as WMS layers, if you have a list of layers with the same endpoint, so it would become a "LayerControl".

In the long run, we could probably focus on time/date controlling with this element (with a calendar date/time picker UI etc.) and not make it a generic "url param control" element.

## Proposal
How about we rename the property to something like `currentItem` or `currentElement` or `currentStep`?
