### ISSUE TITLE
Storytelling "sections"

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/EOxElements#687]
Edit: see https://github.com/EOX-A/EOxElements/issues/687#issuecomment-1961093038 - it is recommended to use `h2` sections

----------
Original:

The initial way of describing "sections" would be using `h1` tags; this would also create a nav entry for each section (as described in #682).
There might be cases where `h2` are used instead of `h1`, because of the way how GitHub renders headings (`h1` and `h2` with underlines, the rest without).

So even if
```
# Section
## Section-step
## Section-step
```
is preferable due to markdown syntax, actually
```
## Section
### Section-step
### Section-step
```
is preferable due to markdown rendering on GitHub. We could have mixed approaches like
```
# Section
### Section-step
### Section-step
# Section
## Section-step
## Section-step
```
but in general, it would be nice to have a flexible approach about this. For example, we could either check the first heading and define this heading level as section (so if the first heading encountered is `h2`, then `h2` is defined as section), or we check for the top-most heading level and take that as section:
```
## Some pre-heading
Foo bar

# Section one

# Section two
```

Another approach could be that we always assume some kind of "hero" and say that one has to be `h1`, the rest of the sections need to be `h2`s:
```
# Hero title of the entire story

## Section one
### Section-step
### Section-step

## Section two
```

This affects the syntax for map section rendering (#686).

**Comment by StefanBrand** [comment]
I can only say that multiple `h1`s are bad: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#avoid_using_multiple_h1_elements_on_one_page

**Comment by santilland** [comment]
I was not aware of that @StefanBrand i think that helps us with the decision making, as i was very unsure about what makes most sense.
If we want to try to align to best practice i guess the last suggestion from @silvester-pari makes the most sense.

**Comment by silvester-pari** [comment]
Thanks @StefanBrand! That is indeed a good find! Then let's do h2 as sections and h3 as section steps
