### ISSUE TITLE
Support multiple projections

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/EOxElements#702]
Add functionality to init the map with a different projection (like `EPSG:4326`). Bonus points if we implement a projection switcher that allows this on the fly.

**Comment by lubojr** [comment]
Will be very much needed for our planned polar dashboard v5 which has datasets which are both interesting in some Polar projection and EPSG:4326 so on-demand-switcher (replacing existing used OL view with a one with a different projection).

**Comment by RobertOrthofer** [comment]
I will look into it as soon as possible

**Comment by silvester-pari** [comment]
Implemented in https://github.com/EOX-A/EOxElements/pull/730
