### ISSUE TITLE
Item Filter Items should be deselectable

### ISSUE THREAD

**Issue by lubojr** [EOX-A/EOxElements#713]
As a configurable feature I would like the ItemFilter items to be deselectable as well.
As a default current behavior (single select without option to deselect) is fine.

**Comment by silvester-pari** [comment]
We currently use radio inputs for the result list, and I believe there is no way to deselect a radio input. We could consider using something else instead of radio buttons.

**Comment by santilland** [comment]
@silvester-pari is it possible to deselect items now that radio buttons are no longer used?

**Comment by silvester-pari** [comment]
Yes, now results can be selected and deselected
