### ISSUE TITLE
Redundant imports in Storybook stories

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/EOxElements#745]
Currently some story files import other elements (example: [layercontrol](https://github.com/EOX-A/EOxElements/blob/main/elements/layercontrol/stories/layercontrol.stories.js#L1)), which results in big bundle sizes (see screenshot 1) and issues with [re-defining custom elements](https://github.com/EOX-A/EOxElements/issues/304) (see screenshot 2).

I believe that storybook shares its bundles between stories, so importing the element in its dedicated story file should be enough to share it across all other stories (without the need to re-import them there).

## Screenshots
![image](https://github.com/EOX-A/EOxElements/assets/26576876/0827e1f0-6ded-462e-b920-db7167550d60)
![image](https://github.com/EOX-A/EOxElements/assets/26576876/7261b27c-00be-45c1-9ed9-9a9f5fd72297)

**Comment by silvester-pari** [comment]
I tried removing all redundant imports (see https://github.com/EOX-A/EOxElements/pull/746), but unfortunately this doesn't work, it does seem that the element import in each story is required.

Further research is needed, maybe we can import all elements once in a global file instead?

**Comment by silvester-pari** [comment]
The approach with importing all elements in the main preview file works (see https://github.com/EOX-A/EOxElements/pull/746/commits/94bbf5b2d6c8e501ad9589c0e5a787f5af2205c3) and it reduces element story bundle size, but not the overall bundle size:

![image](https://github.com/EOX-A/EOxElements/assets/26576876/c66d903c-6c94-44a4-825e-1c4d412d7760)

**Comment by santilland** [comment]
having a main location for importing seems like a good approach! Let's use this for now, we can always focus on improving bundle size in the future
