### ISSUE TITLE
Geolocation control asks for location access even when centerWhenReady is false

### ISSUE THREAD

**Issue by StefanBrand** [EOX-A/EOxElements#793]
I expect the Geolocation control to stay silent until I click on it. Then it should ask for location access permission.

My configuration:

```js
    {
        Geolocation: {
          centerWhenReady: false,
          highAccuracy: true,
          trackAccuracy: true,
        }
    }
```

**Comment by RobertOrthofer** [comment]
Right now, the button will "center" on the position, the position however is already displayed on the map.

This change would mean that the button is always visible, but the position of the user would only be visible after clicking the "center" button - is this the desired behaviour?

**Comment by silvester-pari** [comment]
I think this would be the familiar functionality provided by other map tools.
Initially, no POI is shown, but once a user clicks on the button it "enables" GPS, draws the POI and centers the map on the POI. After subsequent button clicks it returns the user to the center in case he/se navigated away.

**Comment by RobertOrthofer** [comment]
Ok, i can look into this
