### ISSUE TITLE
Default Geolocation control icon is broken

### ISSUE THREAD

**Issue by StefanBrand** [EOX-A/EOxElements#794]
When `buttonIcon` is not overriden, the Geolocation control displays only a placeholder icon:

![image](https://github.com/EOX-A/EOxElements/assets/8948865/b89f228b-9735-4020-9e71-5639ca102baa)

**Comment by RobertOrthofer** [comment]
Can you provide a minimal example? It seems to work in the map story

**Comment by silvester-pari** [comment]
I think a button icon has to be provided, as i don't see any default: https://github.com/EOX-A/EOxElements/blob/main/elements/map/src/controls/Geolocation.ts#L49

Shall we add a "default" icon? Then I'd prefer to include it into the bundle and not hotlink it.

**Comment by RobertOrthofer** [comment]
![Screenshot 2024-04-02 at 10 31 08](https://github.com/EOX-A/EOxElements/assets/19506147/7fe20bcd-52f1-4a05-bfb6-16a7a08371a3)

The default is just a unicode character, providing a proper icon out-of-the-box would definitely be the better choice. Can EOx provide a suitable graphic?

**Comment by silvester-pari** [comment]
I added a quick PR here: https://github.com/EOX-A/EOxElements/pull/802
