### ISSUE TITLE
Simplemde dependency not loaded when bundle is used inside app

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/EOxElements#807]
![image](https://github.com/EOX-A/EOxElements/assets/26576876/855277a9-165c-4577-99e3-9807a9aad48a)

Shall we include this package (including CSS) in the dependencies and bundle it? If it is big, maybe a second bundle or some other way to import it (to prevent importing it by default) would be nice.

E.g.
```
// without editor
import "@eox/storytelling

// with editor
import @eox/storytelling/dist/storytelling-editor.js
import "@eox/storytelling

// or
import @eox/storytelling/dist/storytelling-editor.js
```

**Comment by santilland** [comment]
I think as we have to relatively separate functions, one only for rendering and one if you want to provide an editor, having separate packages to make the "rendering" only version lighter makes sense to me.
Not sure how much effort this change would mean though.
