### ISSUE TITLE
Dedicated fallback tag

### ISSUE THREAD

**Issue by silvester-pari** [EOX-A/EOxElements#818]
For some sections, e.g. eox-map, it makes sense to provide a dedicated fallback functionality. Something like:

```md
## <!--{ as="eox-map" }-->
![](link/to/fallback/image) <!--{ type="fallback" }-->
//or
Please view this story in eox-storytelling! <!--{ mode="fallback" }-->
```

Not sure if we should use `type` or `mode` or `as`, but it would in any case be good to reuse attributes that we have somewhere else (so maybe `mode`?).

**Comment by srijitcoder** [comment]
`mode="fallback"` would be the appropriate key for this.
