### ISSUE TITLE
SimpleMDE editor sometimes not loading on firefox

### ISSUE THREAD

**Issue by santilland** [EOX-A/EOxElements#821]
On the Storybook entry it works with the same browser, so it seems to be eodash v4 related, not sure if the issue should be here.
I tried to do some comparisons on the dom when working not working because i do not get errors in eodash.
From what i can see the from with class `je-ready` does not seem to be initialized correctly in the eodash instance. The form is empty and does not have the data-theme property.
Hope this can help!

**Comment by silvester-pari** [comment]
@santilland I fear we have a `works on my machine` type of issue :thinking: 
![image](https://github.com/EOX-A/EOxElements/assets/26576876/3dba6a23-a6f6-4760-841b-343e839c1669)

**Comment by santilland** [comment]
This has happened to me also in chrome now a couple of times. It seems to be a timing issue, some kind of race condition, refreshing page usually solves the issue.
It should be possible to reproduce by refreshing the browser multiple times until it happens.
