### ISSUE TITLE
Editor positions outside the parent container

### ISSUE THREAD

**Issue by santilland** [EOX-A/EOxElements#894]
It seems the editor is set on fixed absolute to position and "grows" out the container it is initialized in.
I think the default behavior should be it lives within the container. Maybe if it makes sense we could have an option to use it "full screen mode"

**Comment by srijitcoder** [comment]
@santilland Can you share a screenshot of how it is looking right now?

**Comment by santilland** [comment]
![image](https://github.com/EOX-A/EOxElements/assets/4036819/5f4fa654-595b-4701-a091-b07610a41490)
![image](https://github.com/EOX-A/EOxElements/assets/4036819/b08006c2-705f-415a-bbc0-b5b121fe1ed5)

@srijitcoder here is an example (the navigation options are behind the editor)

**Comment by santilland** [comment]
@srijitcoder looking at it now, it seems the container actually uses the full height, but has a padding to reserve the navbar room:
![image](https://github.com/EOX-A/EOxElements/assets/4036819/e70da8d9-0593-473b-ad62-f52b7b9a96b3)
Maybe that is the issue? So it is still within the container but "ignores" the padding
