### ISSUE TITLE
when hiding editor it is still possible to interact with the editor buttons on top

### ISSUE THREAD

**Issue by santilland** [EOX-A/EOxElements#904]
When the editor is set to invisible mouse hover and click functionality is still possible for the editor buttons.
![Screenshot from 2024-04-30 11-27-15](https://github.com/EOX-A/EOxElements/assets/4036819/537ee674-4966-4d59-96fa-5f15fd6c08c7)
![image](https://github.com/EOX-A/EOxElements/assets/4036819/885ec59b-4942-4d2a-8b9a-202cb5ab217d)

**Comment by santilland** [comment]
Maybe related to #884 ?

**Comment by srijitcoder** [comment]
@santilland It was a silly bug 

#### Resolved here - 
- #905
