### ISSUE TITLE
Control for viewing the loading state

### ISSUE THREAD

**Issue by StefanBrand** [EOX-A/EOxElements#911]
_Related to #443 and having in mind the question whether all events should be bubbled up: https://github.com/EOX-A/EOxElements/issues/443#issuecomment-1820862029_

We would like to show the user when the map is loading. I was thinking, it could be a control that shows a loading spinner between `loadstart` and `loadend` events. 

Alternatively, or in addition, a `loading` property could be exposed that allows handling the loading state outside of the `eox-map`.

**Comment by RobertOrthofer** [comment]
Do you want to create a loading indicator like this: https://openlayers.org/en/latest/examples/load-events.html ? 
The easiest way of doing this is by emitting the `loadstart`-event, just like we are already emitting the `loadend`-Event. Would this be sufficient? I suppose we can also create a `loading`-Event, with a boolean value of the loading state.

**Comment by RobertOrthofer** [comment]
Ah, I should read from the start. Yes, a control might be the most intuitive. Can you provide a graphic that we can use as a default spinner?

**Comment by StefanBrand** [comment]
Nope, I don't, but I just found this neat website that lets you create spinners under a [public domain license](https://loading.io/license#free-license) : https://loading.io/
