### ISSUE TITLE
Trigger an event that signals when OL map has mounted

### ISSUE THREAD

**Issue by StefanBrand** [EOX-A/EOxElements#914]
Follow-up of #443 and #911
___

Currently it is not possible to find out when the `.map` property is no longer `undefined`, i.e. when the OL map has been instantiated. Having an event that is triggered after the OL map has been instantiated would make it possible to attach listeners to the OL map directly. There would be no need of bubbling up all events from the OL map, as discussed in #443. #911 could also be handled more easily from the client (while still being a possible candidate for inclusion in the `eox-map`).

**Comment by santilland** [comment]
I remembered seeing an event you can react to called 'loadend'. (https://eox-a.github.io/EOxElements/?path=/docs/elements-eox-map--docs#api at the end)
Not sure if this is not working as expected or it is not triggering at the correct time? Or maybe something else all together?
This should cover this issue in principle, right?

**Comment by StefanBrand** [comment]
My understanding is that `loadend` bubbles up the [OL `loadend` event](https://openlayers.org/en/latest/apidoc/module-ol_MapEvent-MapEvent.html#event:loadend). For the use-cases of #443 and #911, this is not what we want. We would like to attach listeners for the `moveend` (#443) and `loadstart` (#911) events. However, it is not transparent at which point in time the `.map` property of the `eox-map` element references the OL map instance.

**Comment by RobertOrthofer** [comment]
The map is mounted inside Lits `firstUpdated`-Hook (https://lit.dev/docs/v1/components/lifecycle/#firstupdated), this is also were we set the target of the map. I'm no Lit expert, but if we cannot listen to this natively we can emit the `mapmounted`-event there
