### ISSUE TITLE
No error handling when zoomed in too much in Map

### ISSUE THREAD

**Issue by viktoraronfarkas** [EOX-A/EOxElements#933]
If I zoom in too much on the map, I get my console flooded by error messages, because no images exist over a certain zoom level. Maybe this should be handled, but I am not sure, I am opening this issue to start a conversation about it.

![ScreenRecording2024-05-08at13 50 10-ezgif com-video-to-gif-converter (1)](https://github.com/EOX-A/EOxElements/assets/49757700/cb2b1452-12d5-438d-a909-27254ab94e0f)

**Comment by RobertOrthofer** [comment]
this means that the `maxZoom` of the layer/source is not set correctly. If you know the zoom limits beforehand, you can pass the value and no tiles will be fetched

**Comment by silvester-pari** [comment]
I also think this is expected behavior if the min/max zoom are not set. Probably nothing what the map can "guess".
