### ISSUE TITLE
few eox-map storybook configs are not working

### ISSUE THREAD

**Issue by lubojr** [EOX-A/EOxElements#951]
Following storybook entries are not loading for me in eox-map docs

- [ ] VectorLayer
- [ ] Vector Tile Layer
- [x] STAC Layer
- [ ] Group Layer
- [ ] Controls
- [ ] Hover Select
- [ ] Click Select

**Comment by silvester-pari** [comment]
This seems to be a bug introduced in eox-map, as it concerns all examples without any `zoom` set. Except the STAC Layer, but that works well for me:

![image](https://github.com/EOX-A/EOxElements/assets/26576876/1c341616-1ba0-4392-88c4-7e31c4558f5c)
